In [1]:
import numpy as np

In [6]:
scores = np.array([95, 88, 82, 76, 91, 85, 70, 78, 88])
scores

array([95, 88, 82, 76, 91, 85, 70, 78, 88])

In [7]:
print(f"shape={scores.shape}  dtype={scores.dtype}  ndim={scores.ndim}")

shape=(9,)  dtype=int64  ndim=1


In [3]:
ranks = np.arange(1, 10)

In [8]:
print(f"shape={ranks.shape}  dtype={ranks.dtype}  ndim={ranks.ndim}")

shape=(9,)  dtype=int64  ndim=1


In [11]:
zeros_board = np.zeros((2, 4))
zeros_board

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [15]:
print(f"shape={zeros_board.shape}  dtype={zeros_board.dtype}  ndim={zeros_board.ndim}")

shape=(2, 4)  dtype=float64  ndim=2


In [5]:
percentiles = np.linspace(0, 100, 5)
percentiles

array([  0.,  25.,  50.,  75., 100.])

In [16]:
print(f"shape={percentiles.shape}  dtype={percentiles.dtype}  ndim={percentiles.ndim}")

shape=(5,)  dtype=float64  ndim=1


# Indexing and Slicing

In [13]:
 scores[-1]

np.int64(88)

In [14]:
scores[0:3]

array([95, 88, 82])

In [17]:
percentiles[1:3]

array([25., 50.])